name: TallNether
main: com.minefit.XerxesTireIron.TallNether.TallNether
version: 1.2.5
website: https://github.com/OtakuMegane/TallNether
author: XerxesTireIron
description: Makes nether 256 blocks tall
load: startup