name: TallNether
main: com.minefit.xerxestireiron.tallnether.TallNether
version: 1.4.1
website: https://github.com/OtakuMegane/TallNether
author: XerxesTireIron
description: Makes the nether 256 blocks tall
load: startup