name: TallNether
main: com.minefit.xerxestireiron.tallnether.TallNether
version: 2.5
website: https://github.com/OtakuMegane/TallNether
author: XerxesTireIron
description: Makes the nether 256 blocks tall
load: startup
api-version: 1.13