name: TallNether
main: com.minefit.XerxesTireIron.TallNether.TallNether
version: 1.4
website: https://github.com/OtakuMegane/TallNether
author: XerxesTireIron
description: Makes the nether 256 blocks tall
load: startup